# Generated by Django 2.2.6 on 2019-10-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REFridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderQuantity', models.IntegerField()),
                ('OrderPrice', models.IntegerField()),
                ('BuyerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_requests_created', to='REFridge.Buyer')),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_requests_created', to='REFridge.Product')),
                ('SellerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_requests_created', to='REFridge.Seller')),
                ('SellerStockID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_requests_created', to='REFridge.SellerStock')),
            ],
            options={
                'unique_together': {('SellerID', 'BuyerID', 'ProductID', 'SellerStockID')},
            },
        ),
    ]
