# Generated by Django 2.2.6 on 2019-10-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REFridge', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='Blatitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='Blongitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='Blatitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='Blongitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
