# Generated by Django 2.2.6 on 2019-10-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REFridge', '0003_auto_20191025_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='Blatitude',
            new_name='Slatitude',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='Blongitude',
            new_name='Slongitude',
        ),
    ]
