# Generated by Django 2.2.6 on 2019-10-25 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REFridge', '0004_auto_20191025_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='BuyerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fridge_requests_created', to='REFridge.Buyer'),
        ),
    ]
