# Generated by Django 2.2.6 on 2019-11-05 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REFridge', '0005_fridge_buyerid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fridge',
            unique_together={('BuyerID', 'ProductID')},
        ),
    ]
